name 'stderr-jenkins'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures stderr-jenkins'
long_description 'Installs/Configures stderr-jenkins'
version '0.1.0'
